#cloud-config
# Ubuntu Server 24.04 LTS autoinstall configuration
# Calls existing working anvil install process

autoinstall:
  version: 1

  # Locale and keyboard
  locale: en_US.UTF-8
  keyboard:
    layout: us
    variant: ''

  # Network - DHCP for quick setup
  network:
    version: 2
    ethernets:
      all-en:
        match:
          name: "en*"
        dhcp4: true
      all-eth:
        match:
          name: "eth*"
        dhcp4: true

  # Storage - simple LVM setup
  storage:
    layout:
      name: lvm
      sizing-policy: all

  # Identity - CUSTOMIZE THESE
  identity:
    hostname: ubuntu-node
    username: deploy
    # Default password: "deploy123"
    # Generate your own: openssl passwd -6 YourPasswordHere
    password: "$6$saltsalt$qoMuYLhl7B.WwgdmXALPkvy9T2qT5Dm1caMs7qKYOThcHEsivvkPFSVrPZMdtvjDdpUtRGDwhagMSgf3YAmVT1"

  # SSH configuration
  ssh:
    install-server: true
    allow-pw: true
    # Add your SSH public key here for passwordless login:
    authorized-keys: []
      # - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGExampleKeyHere your-email@example.com"

  # Packages to install during setup
  packages:
    - curl
    - wget
    - git
    - openssh-server

  # Disable automatic updates during installation
  apt:
    geoip: true
    disable_components: []
    preserve_sources_list: false

  # User data - additional cloud-init config
  user-data:
    timezone: America/New_York
    package_update: true
    package_upgrade: false  # Don't upgrade during install (faster)
    # Ensure deploy user is in sudo group (usually automatic, but explicit is better)
    users:
      - name: deploy
        groups: [sudo, users]
        shell: /bin/bash

  # Late commands - run after installation
  late-commands:
    # Configure passwordless sudo for deploy user (created by identity section)
    # User will be added to sudo group automatically by identity config
    - |
      echo 'deploy ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/deploy
      chmod 0440 /target/etc/sudoers.d/deploy

    # Pre-create log file with proper ownership for deploy user
    - |
      touch /target/var/log/first-boot.log
      chown 1000:1000 /target/var/log/first-boot.log
      chmod 0644 /target/var/log/first-boot.log

    # Auto-show provisioning logs on user login
    - |
      cat > /target/etc/profile.d/first-boot-monitor.sh <<'EOFPROFILE'
      #!/bin/bash
      # Auto-show first-boot logs if provisioning is in progress

      if systemctl is-active --quiet first-boot.service 2>/dev/null; then
          echo "========================================"
          echo "⚙️  SYSTEM PROVISIONING IN PROGRESS"
          echo "========================================"
          echo ""
          echo "Anvil is automatically configuring this system."
          echo "Following provisioning logs (Ctrl+C to detach):"
          echo ""
          sleep 2
          sudo journalctl -u first-boot.service -f
      elif [ -f /var/lib/first-boot-complete ]; then
          # Provisioning done, show completion message once
          if [ ! -f "$HOME/.first-boot-notified" ]; then
              echo "✅ System provisioning completed successfully!"
              echo "   Check /var/log/first-boot.log for details"
              touch "$HOME/.first-boot-notified"
          fi
      fi
      EOFPROFILE
      chmod +x /target/etc/profile.d/first-boot-monitor.sh

    # Create systemd service for first-boot
    - |
      cat > /target/etc/systemd/system/first-boot.service <<'EOFSERVICE'
      [Unit]
      Description=First boot provisioning (calls anvil)
      After=network-online.target
      Wants=network-online.target
      ConditionPathExists=!/var/lib/first-boot-complete

      [Service]
      Type=oneshot
      User=deploy
      ExecStart=/usr/local/bin/first-boot.sh
      ExecStartPost=/usr/bin/sudo /usr/bin/touch /var/lib/first-boot-complete
      StandardOutput=journal+console
      StandardError=journal+console
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
      EOFSERVICE

    # Download first-boot script from GitHub
    - curtin in-target --target=/target -- curl -fsSL https://raw.githubusercontent.com/Beta-Techno/boot/main/scripts/first-boot.sh -o /usr/local/bin/first-boot.sh

    # Make it executable
    - curtin in-target --target=/target -- chmod +x /usr/local/bin/first-boot.sh

    # Enable the service
    - curtin in-target --target=/target -- systemctl enable first-boot.service

    # Set timezone
    - curtin in-target --target=/target -- timedatectl set-timezone America/New_York

  # Shutdown after installation
  shutdown: reboot
